// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjydxIpyAbWsdNZw8jsO29xfyCcvVuZs',
    appId: '1:775834450902:web:b5a70d3220491d4aac4277',
    messagingSenderId: '775834450902',
    projectId: 'n64-catalogo',
    authDomain: 'n64-catalogo.firebaseapp.com',
    storageBucket: 'n64-catalogo.firebasestorage.app',
    measurementId: 'G-FS07E4SHLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-aUGajBiDiPuTviwK5fYjebqt_CI7saQ',
    appId: '1:775834450902:android:011cd777bab8ebf0ac4277',
    messagingSenderId: '775834450902',
    projectId: 'n64-catalogo',
    storageBucket: 'n64-catalogo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVf0ic6AlajbD0TOYhIk8RFwNMzvoLVQo',
    appId: '1:775834450902:ios:40c74d9ac8ae8037ac4277',
    messagingSenderId: '775834450902',
    projectId: 'n64-catalogo',
    storageBucket: 'n64-catalogo.firebasestorage.app',
    iosBundleId: 'com.example.n64Catalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVf0ic6AlajbD0TOYhIk8RFwNMzvoLVQo',
    appId: '1:775834450902:ios:40c74d9ac8ae8037ac4277',
    messagingSenderId: '775834450902',
    projectId: 'n64-catalogo',
    storageBucket: 'n64-catalogo.firebasestorage.app',
    iosBundleId: 'com.example.n64Catalogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhjydxIpyAbWsdNZw8jsO29xfyCcvVuZs',
    appId: '1:775834450902:web:d94f3fb925cb7eeaac4277',
    messagingSenderId: '775834450902',
    projectId: 'n64-catalogo',
    authDomain: 'n64-catalogo.firebaseapp.com',
    storageBucket: 'n64-catalogo.firebasestorage.app',
    measurementId: 'G-DH2V1759WC',
  );
}
